server.port: 8082

spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
    password: 123456
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8000
          order: 0
          predicates:
            - Path=/foo/**
          filters:
            - StripPrefix=1
            - name: RateLimiter
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
  hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
