server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: image/png,image/jpeg,image/jpg,text/html,application/javascript,text/css,application/octet-stream,application/json

eureka:
  client:
    service-url:
      defaultZone:  http://admin:ourblue@192.168.1.22:8761/eureka/
  instance:
    instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    ip-address: 192.168.1.222
    prefer-ip-address:  true

jdcloud:
  token:
    interceptor:
      enable: true
  grayRelease:
    interceptor:
      enable: true
  quotation:
    warning:
      phone:  85263516042
  oauth2:
    client:
      id : ${security.oauth2.resource.id}
      accessTokenUrl :  ${security.oauth2.client.access-token-uri}
      clientId :  ${security.oauth2.client.clientId}
      clientSecret :  ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  aliyun:
    uploadPath: test/


###security
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: jdcloud-client-walletbiz
      clientSecret: jdcloudClientSecret
      access-token-uri :  http://192.168.1.22:8087/oauth/token
      user-authorization-uri :  http://192.168.1.22:8087/oauth/authorize
    resource:
      user-info-uri:  http://192.168.1.22:8087/user
      prefer-token-info:  false
      jwt.key-uri:  http://192.168.1.22:8087/oauth/token_key

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: bitrade_app
      password: EMst,DfjusI1SPsw!=
      url: jdbc:mysql://192.168.1.63:3306/jdcloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query: SELECT 1
      test-while-idle:  true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis:  00006
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        login-username: admin
        login-password: Admin10086
  application:
    name: wallet-biz:@pom.artifactId@
  redis:
    cluster:
      nodes:  192.168.1.74:7000,192.168.1.74:7001,192.168.1.74:7002,192.168.1.62:7000,192.168.1.62:7001,192.168.1.62:7002
    password: Qdsemmde_sde@#!Bitrade
    pool:
      max-idle: 30
      min-idle: 10
      max-active: 1000
      max-wait: 1000
    timeout: 10000
    database: 0

mybatis:
  mapper-locations:
    classpath: mapper/*.xml
    type-aliases-package: com.jdcloud.provider.pojo

feign:
  hystrix:
    enabled: true

swagger:
  exclude-path: /error ,/auditevents,/env,/fundAccount, /refresh , /health, /heapdump,/hystrix.stream/** ,/jolokia/** , /loggers ,/auditevents.json ,/env/reset , /env.json , /env/ , /health.json, /heapdump.json,/metrics ,/shutdown ,/shutdown.json , /service-registry/instance-status , /metrics.json ,/loggers.json ,/refresh.json, /env/{name},/loggers/{name},/metrics/{name},/archaius,/archaius.json,/autoconfig,/autoconfig.json,/beans,/beans.json,/configprops,/configprops.json,/dump,/dump.json,/features,/features.json,/info,/info.json,/mappings,/mappings.json,/trace,/trace.json

btc:
  point:
    url: http://58.82.251.195:8888
    user: a61d8ccbf458819d
    password: df81ae8d7de19032
  network:
    main: true