#svc_name: currency

data:
  #model-package: com.*.pojo.model.*
  #mapper-locations: classpath*:/__default_SQL/**/I*DAO.xml,classpath*:/SQL/**/I*DAO.xml
  application:
    name: admin
  register-with-eureka: false
  fetch-registry: false

#dubbo.protocol.port: 20883

server:
  port: 2091

spring:
#  application:
#    name: currency
  profiles:
    active: common
  
  ###ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT HTML5
    mode: LEGACYHTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html; charset=UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    #配置页面后缀 
    suffix: .html
