
### 开发环境。

---
data:
  datasource:
    ip: 154.222.138.249
    db: bit_trade_dev
    password: xlkj@lm20190627
  # 地址。
  addr:
    auth: http://localhost:8087/
    gateway: http://localhost:9000/auz/
    
    auz: ${data.addr.auth}
    #auz: ${data.addr.gateway}


dubbo:
  registry:
    address: N/A
