
### 开发环境。

---
data:
  self-IP: ${spring.cloud.client.ip-address}
  
  datasource:
    ip: 154.222.138.5 # 154.222.138.249
    db: bit_trade_dev
    password: xlkj@lm20190627
  
  # 地址。
  addr:
    auth: http://localhost:8087/
    gateway: http://localhost:9000/auz/
    
    auz: ${data.addr.auth}
    #auz: ${data.addr.gateway}
  
  # 注册中心。
  eureka:
    serviceUrl: admin:admin@localhost:8761
  
  rabbitmq:
    #虚拟空间地址
    virtual-host: /dev


#mybatis-plus:
#  configuration:
    #logImpl: org.apache.ibatis.logging.stdout.StdOutImpl


dubbo:
  registry:
    address: N/A
