#svc_name: currency

data:
  #model-package: com.*.pojo.model.*
  #mapper-locations: classpath*:/__default_SQL/**/I*DAO.xml,classpath*:/SQL/**/I*DAO.xml
  application:
    name: entrust
  register-with-eureka: false
  fetch-registry: false

dubbo.protocol.port: 20882

#server:
#  port: 8910

spring:
#  application:
#    name: currency
  profiles:
    active: common, dubbo_provider, dubbo_consumer, amqp