data:
  application:
    name: uac
  register-with-eureka: true
  fetch-registry: true

dubbo.protocol.port: 20881

server:
  port: 8901

bitTrade:
  profile: test/

spring:
  profiles:
    active: common, dubbo_provider, dubbo_consumer
  mvc:
    throw-exception-if-no-handler-found: true
  mail:
    host: smtp.sina.cn
    port: 25
    username: xiao_zichao@sina.cn
    password: Xiaozichao1
    subject: 剑灵科技
    properties: {
      mail.smtp.starttls.enable: true,
      mail.smtp.starttls.required: true,
      mail.smtp.auth: true
    }


sms:
  c5:
    userName: chenzhaoyun
    password: 1adbb3178591fd5bb0c248518f39bf6d
    url: http://hk.5c.com.cn/api/send/index.php
    apiKey: 7caeca667a7cfa742bdfcdf6767be54c

upload:
  aliyun:
    accessKeyId: LTAIEBmj0nhaZrVy
    accessKeySecret: KXX8XvVoLavNOOVldAWiuMljTyZKr8
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketDomain: https://bitrade-sz-oss.oss-cn-shenzhen.aliyuncs.com/
    bucketName: bitrade-sz-oss
    region: oss-cn-shenzhen