---
dubbo:
  # dubbo 信息
  application:
    id: service-consumer
    name: service-consumer
  registry:
    #address: zookeeper://127.0.0.1:2181
    address: N/A
    check: false
  monitor:
    protocol: registry
  consumer:
    check: false
    timeout: 10000
#  reference:
#    check: false