spring:
  application:
    name: ${spring.application_name:eureka-cluster}

---
#server:
#  port: 8761

eureka:
  port_1: 1761
  port_2: 1762
  port_3: 1763
  instance:
    hostname: localhost
    prefer-ip-address: true
    #ip-address: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:@project.version@
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${eureka.port_1}/eureka/,http://${eureka.instance.hostname}:${eureka.port_2}/eureka/,http://${eureka.instance.hostname}:${eureka.port_3}/eureka/
      defaultZone: http://admin:admin@localhost:8761/eureka/
    register-with-eureka: ${data.register-with-eureka:true}
    fetch-registry: ${data.fetch-registry:true}
