---
dubbo:
  # dubbo 信息
  application:
    id: service-provider
    name: service-provider
  # 协议信息
  protocol:
    id: dubbo
    name: dubbo
    
    #port: 20880
    #port: ${data.dubbo.protocol.port}
    
  # 注册中心信息
  registry:
    id: my-registry
    protocol: zookeeper
    
    #address: N/A
    #address: 127.0.0.1:2181
    #address: zookeeper://127.0.0.1:2181
    #address: zookeeper://localhost:2181
    #address: zookeeper://192.168.1.180:2181?backup=192.168.1.180:2182,192.168.1.180:2183
    #address: ${data.dubbo.registry.address}
    
  monitor:
    #protocol: registry
    #address: 监控IP:7070
  provider:
    timeout: 5000
  scan:
    # like the @EnableDubbo ?
    # Base packages to scan Dubbo Components (e.g., @Service, @Reference)
    #basePackages: cn.itsource.dubbo.api.impl

#demo.service.version=1.0.0