spring:
  rabbitmq:
    #服务器ip
#    host: localhost
    host: 154.222.138.211
    #host: 154.222.138.249
    #端口号
    port: 5672
    #用户名
    username: o
    #密码
    password: o
    #虚拟空间地址
    virtual-host: /tmp
    publisher-confirms: true
    publisher-returns: true
    listener:
      # 手动方式应答
      acknowledge-mode: MANUAL

# https://www.cnblogs.com/hhhshct/p/9718063.html