spring:
  redis:
    host: 47.107.74.74
    port: 6379
    password: woaini123
    cacheNames:
      user-wallet-judge: 300
      coin-config: 300
      user-wallet: 300
  profiles:
    active: dev
  task:
    scheduling:
      pool:
        size: 16 # 设置scheduling的线程池大小默认只有一个
