spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/wallet?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&pinGlobalTxToPhysicalConnection=true
      username: root
      password: 123456
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      use-unfair-lock: true
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validationQuery: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      keep-alive: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.micro
  global-config:
    db-config:
      id-type: auto

btc:
  config-wallet:
    encrypt-key: 1234567812345678  #最少16位   8的倍数
  user-wallet:
    encrypt-key: 1234567812345678  #最少16位   8的倍数
  network:
    main: false   #测试网络
  point:
    url: http://43.243.177.7:18000
    user: 123456
    password: abcdef
  fee_rate:
    url: https://bitcoinfees.earn.com/api/v1/fees/recommended