## ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓下面配置（此配置文件）为3个环境公用↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓服务器配置 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #
server:
  # 建议不要直接写死，可以在VM options中通过-DServer.port=8080配置
  port: 8086
  tomcat:
    uri-encoding: UTF-8


